version: '3.8'

services:
  backend:
    container_name: dvkn-backend2
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.production
    ports:
      - "8081:8081"
    networks:
      - dvkn-network
    restart: unless-stopped

networks:
  dvkn-network:
    external: true